#!/bin/sh
echo "Folder Build Started->"

mkdir js;
mkdir scss;
mkdir css;
mkdir images;
mkdir pageviews;
touch gulpfile.js

echo "Folder Build Complete!"

echo "File Compiler Started->"

printf "<!DOCTYPE html>\n<html>\n<head>\n<title></title>\n<link href="css/main.css" rel="stylesheet" type="text/css" />\n<!-- <script src="http://code.jquery.com/jquery-2.2.3.min.js"></script> -->\n<!-- <script src="http://underscorejs.org/underscore-min.js"></script> -->\n<script src="js/app.js"></script>\n</head>\n\n<body></body>\n</html>" > index.html;
printf "/* jslint browser: true, esnext: true */" > js/app.js;
printf "@import \"bourbon/bourbon\";\n@import \"neat/neat\";" > scss/main.scss;

echo "File Compiler Complete!"

echo "Installing Bourbon/Neat"
cd scss;
bourbon install;
neat install;

cd ..

echo "Gulp Programs Installing via NPM"

npm install gulp gulp-sass gulp-ng-annotate gulp-browser gulp-uglify

echo "Gulp Programs Install"

echo "Progress Reached 100%"
