#!/bin/sh
echo "Folder Build Started->"

mkdir js;
mkdir scss;
mkdir css;
mkdir images;
mkdir pageviews;
touch gulpfile.js

echo "Folder Build Complete!"

echo "File Compiler Started->"

printf "<!DOCTYPE html>\n<html>\n<head>\n\t<title></title>\n\t<link href="css/main.css" rel="stylesheet" type="text/css" />\n\t<!-- <script src="http://code.jquery.com/jquery-2.2.3.min.js"></script> -->\n\t<!-- <script src="http://underscorejs.org/underscore-min.js"></script> -->\n\t<script src="js/app.js"></script>\n</head>\n\n<body></body>\n</html>" > index.html;
printf "/* jslint browser: true, esnext: true */" > js/app.js;
printf "@import \"bourbon/bourbon\";\n@import \"neat/neat\";" > scss/main.scss;
printf "/* npm install --save-dev gulp gulp-sass gulp-jade gulp-babel gulp-babel babel-preset-es2015 gulp-ng-annotate gulp-browser gulp-uglify */ \n var gulp\t= require(\"gulp\"); \n var sass\t= require(\"gulp-sass\"); \n var babel\t= require(\"gulp-babel\"); \n var ngAnnotate\t= require(\"gulp-ng-annotate\"); \n var gulpBrowser\t= require(\"gulp-browser\"); \n var uglify\t= require(\"gulp-uglify\"); \n var gulpJade\t= require(\"gulp-jade\"); \n\n gulp.task(\'default\'\, \[\'html\'\, \'pageviews\'\, \'css\'\, \'js\'\, \'images\'\]);\n\n gulp.task(\'html\'\, function()\{\n\t return gulp.src(\'\./\*.html\')\.pipe(gulp.dest(\'\./public/\'));\n\});"
echo "File Compiler Complete!"

echo "Installing Bourbon/Neat"
cd scss;
bourbon install;
neat install;

cd ..

echo "Gulp Programs Installing via NPM"

npm install gulp gulp-sass gulp-ng-annotate gulp-browser gulp-uglify

echo "Gulp Programs Install"

echo "Progress Reached 100%"
